[versions]
arrow = "1.1.2"
dokka = "1.7.0"
arrowGradleConfig = "0.10.3-alpha.3"
kotlin = "1.7.0"
kotest = "5.3.1"
kotlinBinaryCompatibilityValidator = "0.10.1"
detekt = "1.20.0"
animalsniffer = "1.5.4"
jacksonModuleKotlin = "2.13.3"
animalsnifferAnnoation = "1.21"

[libraries]
arrowAnnotations = { module = "io.arrow-kt:arrow-annotations", version.ref = "arrow" }
arrowCore = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrowCoreTest = { module = "io.arrow-kt:arrow-core-test", version.ref = "arrow" }
arrowOptics = { module = "io.arrow-kt:arrow-optics", version.ref = "arrow" }
jacksonModuleKotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jacksonModuleKotlin" }
kotest-assertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-frameworkEngine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-runnerJUnit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
animalsniffer-annotation = {module = "org.codehaus.mojo:animal-sniffer-annotations", version.ref = "animalsnifferAnnoation"}

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
arrowGradleConfig-formatter = { id = "io.arrow-kt.arrow-gradle-config-formatter", version.ref = "arrowGradleConfig" }
arrowGradleConfig-kotlin = { id = "io.arrow-kt.arrow-gradle-config-kotlin", version.ref = "arrowGradleConfig" }
arrowGradleConfig-nexus = { id = "io.arrow-kt.arrow-gradle-config-nexus", version.ref = "arrowGradleConfig" }
arrowGradleConfig-publish = { id = "io.arrow-kt.arrow-gradle-config-publish", version.ref = "arrowGradleConfig" }
arrowGradleConfig-versioning = { id = "io.arrow-kt.arrow-gradle-config-versioning", version.ref = "arrowGradleConfig" }
kotlin-binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinBinaryCompatibilityValidator" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
animalsniffer = { id = "ru.vyarus.animalsniffer", version.ref = "animalsniffer" }
