name: "arrow-integrations: build documentation"

on: pull_request

jobs:
  arrow-integrations_build_documentation:

    env:
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: macos-latest
    timeout-minutes: 90

    steps:
    - uses: actions/checkout@v3
    - name: Generate API doc
      run: ./gradlew dokka
    - name: Validation
      run: ./gradlew :arrow-docs:runAnk
