name: "arrow-integrations: build"

on: pull_request

jobs:
  arrow-integrations_build:

    env:
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: macos-latest
    timeout-minutes: 90

    steps:
    - uses: actions/checkout@v3
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Build
      run: |
        ./gradlew build
    - name: Prepare test reports
      if: ${{ always() }}
      run: |
        mkdir test-reports
        for report in `ls -d ./**/build/reports/tests/test`; do
          arrow_module=$(echo $report | cut -d/ -f2)
          cp -r $report test-reports/$arrow_module
        done
    - name: Make test reports available to download
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: test-reports
